spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 742607128
        url: jdbc:mysql://localhost:3306/easyweather?characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
      jpa:
        show-sql: true
      application:
        name: easyweather

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zrf.easyweather.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true